# Site
name: "Ramen Bytes"
title: "Ramen Bytes"
description: "Sharing learnings and thoughts on tech related topics as an early career engineer, one ramen bowl at a time!"
logo: "assets/images/ramenbytes-logo.png"
favicon: "assets/images/ramenbytes-logo.ico"
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  emmanuelle:
    name: Emmanuelle
    gravatar: 6fc9b25b55321770985c82adf435f912
    display_name: Emmanuelle
    web: https://www.ramenbytes.fr
    twitter: https://twitter.com/ManuLejeail
    description: "I am a Software Engineer that works on application security and likes to put an AI spin on anything I can."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
